/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ForceDeployUpgraderInterface extends ethers.utils.Interface {
  functions: {
    "forceDeploy(tuple[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "forceDeploy",
    values: [
      {
        bytecodeHash: BytesLike;
        newAddress: string;
        callConstructor: boolean;
        value: BigNumberish;
        input: BytesLike;
      }[]
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "forceDeploy",
    data: BytesLike
  ): Result;

  events: {};
}

export class ForceDeployUpgrader extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ForceDeployUpgraderInterface;

  functions: {
    forceDeploy(
      _forceDeployments: {
        bytecodeHash: BytesLike;
        newAddress: string;
        callConstructor: boolean;
        value: BigNumberish;
        input: BytesLike;
      }[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "forceDeploy(tuple[])"(
      _forceDeployments: {
        bytecodeHash: BytesLike;
        newAddress: string;
        callConstructor: boolean;
        value: BigNumberish;
        input: BytesLike;
      }[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  forceDeploy(
    _forceDeployments: {
      bytecodeHash: BytesLike;
      newAddress: string;
      callConstructor: boolean;
      value: BigNumberish;
      input: BytesLike;
    }[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "forceDeploy(tuple[])"(
    _forceDeployments: {
      bytecodeHash: BytesLike;
      newAddress: string;
      callConstructor: boolean;
      value: BigNumberish;
      input: BytesLike;
    }[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    forceDeploy(
      _forceDeployments: {
        bytecodeHash: BytesLike;
        newAddress: string;
        callConstructor: boolean;
        value: BigNumberish;
        input: BytesLike;
      }[],
      overrides?: CallOverrides
    ): Promise<void>;

    "forceDeploy(tuple[])"(
      _forceDeployments: {
        bytecodeHash: BytesLike;
        newAddress: string;
        callConstructor: boolean;
        value: BigNumberish;
        input: BytesLike;
      }[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    forceDeploy(
      _forceDeployments: {
        bytecodeHash: BytesLike;
        newAddress: string;
        callConstructor: boolean;
        value: BigNumberish;
        input: BytesLike;
      }[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "forceDeploy(tuple[])"(
      _forceDeployments: {
        bytecodeHash: BytesLike;
        newAddress: string;
        callConstructor: boolean;
        value: BigNumberish;
        input: BytesLike;
      }[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    forceDeploy(
      _forceDeployments: {
        bytecodeHash: BytesLike;
        newAddress: string;
        callConstructor: boolean;
        value: BigNumberish;
        input: BytesLike;
      }[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "forceDeploy(tuple[])"(
      _forceDeployments: {
        bytecodeHash: BytesLike;
        newAddress: string;
        callConstructor: boolean;
        value: BigNumberish;
        input: BytesLike;
      }[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
