/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IEthTokenInterface extends ethers.utils.Interface {
  functions: {
    "withdrawWithMessage(address,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "withdrawWithMessage",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "withdrawWithMessage",
    data: BytesLike
  ): Result;

  events: {};
}

export class IEthToken extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IEthTokenInterface;

  functions: {
    withdrawWithMessage(
      _l1Receiver: string,
      _additionalData: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "withdrawWithMessage(address,bytes)"(
      _l1Receiver: string,
      _additionalData: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  withdrawWithMessage(
    _l1Receiver: string,
    _additionalData: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "withdrawWithMessage(address,bytes)"(
    _l1Receiver: string,
    _additionalData: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    withdrawWithMessage(
      _l1Receiver: string,
      _additionalData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdrawWithMessage(address,bytes)"(
      _l1Receiver: string,
      _additionalData: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    withdrawWithMessage(
      _l1Receiver: string,
      _additionalData: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "withdrawWithMessage(address,bytes)"(
      _l1Receiver: string,
      _additionalData: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    withdrawWithMessage(
      _l1Receiver: string,
      _additionalData: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "withdrawWithMessage(address,bytes)"(
      _l1Receiver: string,
      _additionalData: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
