/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IEthToken } from "./IEthToken";

export class IEthTokenFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEthToken {
    return new Contract(address, _abi, signerOrProvider) as IEthToken;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_l1Receiver",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_additionalData",
        type: "bytes",
      },
    ],
    name: "withdrawWithMessage",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];
