/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ComplexUpgraderInterface extends ethers.utils.Interface {
  functions: {
    "upgrade(address,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "upgrade",
    values: [string, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "upgrade", data: BytesLike): Result;

  events: {};
}

export class ComplexUpgrader extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ComplexUpgraderInterface;

  functions: {
    upgrade(
      _delegateTo: string,
      _calldata: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "upgrade(address,bytes)"(
      _delegateTo: string,
      _calldata: BytesLike,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  upgrade(
    _delegateTo: string,
    _calldata: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "upgrade(address,bytes)"(
    _delegateTo: string,
    _calldata: BytesLike,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    upgrade(
      _delegateTo: string,
      _calldata: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "upgrade(address,bytes)"(
      _delegateTo: string,
      _calldata: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    upgrade(
      _delegateTo: string,
      _calldata: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "upgrade(address,bytes)"(
      _delegateTo: string,
      _calldata: BytesLike,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    upgrade(
      _delegateTo: string,
      _calldata: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "upgrade(address,bytes)"(
      _delegateTo: string,
      _calldata: BytesLike,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
