/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DelegateCallerInterface extends ethers.utils.Interface {
  functions: {
    "delegateCall(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "delegateCall",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "delegateCall",
    data: BytesLike
  ): Result;

  events: {};
}

export class DelegateCaller extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DelegateCallerInterface;

  functions: {
    delegateCall(
      _to: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "delegateCall(address)"(
      _to: string,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  delegateCall(
    _to: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "delegateCall(address)"(
    _to: string,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    delegateCall(_to: string, overrides?: CallOverrides): Promise<void>;

    "delegateCall(address)"(
      _to: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    delegateCall(_to: string, overrides?: PayableOverrides): Promise<BigNumber>;

    "delegateCall(address)"(
      _to: string,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    delegateCall(
      _to: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "delegateCall(address)"(
      _to: string,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
