/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IAccountInterface extends ethers.utils.Interface {
  functions: {
    "executeTransaction(bytes32,bytes32,tuple)": FunctionFragment;
    "executeTransactionFromOutside(tuple)": FunctionFragment;
    "payForTransaction(bytes32,bytes32,tuple)": FunctionFragment;
    "prepareForPaymaster(bytes32,bytes32,tuple)": FunctionFragment;
    "validateTransaction(bytes32,bytes32,tuple)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "executeTransaction",
    values: [
      BytesLike,
      BytesLike,
      {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTransactionFromOutside",
    values: [
      {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "payForTransaction",
    values: [
      BytesLike,
      BytesLike,
      {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "prepareForPaymaster",
    values: [
      BytesLike,
      BytesLike,
      {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "validateTransaction",
    values: [
      BytesLike,
      BytesLike,
      {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      }
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "executeTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTransactionFromOutside",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "payForTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "prepareForPaymaster",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validateTransaction",
    data: BytesLike
  ): Result;

  events: {};
}

export class IAccount extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IAccountInterface;

  functions: {
    executeTransaction(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "executeTransaction(bytes32,bytes32,(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    executeTransactionFromOutside(
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "executeTransactionFromOutside((uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    payForTransaction(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "payForTransaction(bytes32,bytes32,(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    prepareForPaymaster(
      _txHash: BytesLike,
      _possibleSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "prepareForPaymaster(bytes32,bytes32,(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
      _txHash: BytesLike,
      _possibleSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    validateTransaction(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "validateTransaction(bytes32,bytes32,(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;
  };

  executeTransaction(
    _txHash: BytesLike,
    _suggestedSignedHash: BytesLike,
    _transaction: {
      txType: BigNumberish;
      from: BigNumberish;
      to: BigNumberish;
      gasLimit: BigNumberish;
      gasPerPubdataByteLimit: BigNumberish;
      maxFeePerGas: BigNumberish;
      maxPriorityFeePerGas: BigNumberish;
      paymaster: BigNumberish;
      nonce: BigNumberish;
      value: BigNumberish;
      reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
      data: BytesLike;
      signature: BytesLike;
      factoryDeps: BytesLike[];
      paymasterInput: BytesLike;
      reservedDynamic: BytesLike;
    },
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "executeTransaction(bytes32,bytes32,(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
    _txHash: BytesLike,
    _suggestedSignedHash: BytesLike,
    _transaction: {
      txType: BigNumberish;
      from: BigNumberish;
      to: BigNumberish;
      gasLimit: BigNumberish;
      gasPerPubdataByteLimit: BigNumberish;
      maxFeePerGas: BigNumberish;
      maxPriorityFeePerGas: BigNumberish;
      paymaster: BigNumberish;
      nonce: BigNumberish;
      value: BigNumberish;
      reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
      data: BytesLike;
      signature: BytesLike;
      factoryDeps: BytesLike[];
      paymasterInput: BytesLike;
      reservedDynamic: BytesLike;
    },
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  executeTransactionFromOutside(
    _transaction: {
      txType: BigNumberish;
      from: BigNumberish;
      to: BigNumberish;
      gasLimit: BigNumberish;
      gasPerPubdataByteLimit: BigNumberish;
      maxFeePerGas: BigNumberish;
      maxPriorityFeePerGas: BigNumberish;
      paymaster: BigNumberish;
      nonce: BigNumberish;
      value: BigNumberish;
      reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
      data: BytesLike;
      signature: BytesLike;
      factoryDeps: BytesLike[];
      paymasterInput: BytesLike;
      reservedDynamic: BytesLike;
    },
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "executeTransactionFromOutside((uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
    _transaction: {
      txType: BigNumberish;
      from: BigNumberish;
      to: BigNumberish;
      gasLimit: BigNumberish;
      gasPerPubdataByteLimit: BigNumberish;
      maxFeePerGas: BigNumberish;
      maxPriorityFeePerGas: BigNumberish;
      paymaster: BigNumberish;
      nonce: BigNumberish;
      value: BigNumberish;
      reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
      data: BytesLike;
      signature: BytesLike;
      factoryDeps: BytesLike[];
      paymasterInput: BytesLike;
      reservedDynamic: BytesLike;
    },
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  payForTransaction(
    _txHash: BytesLike,
    _suggestedSignedHash: BytesLike,
    _transaction: {
      txType: BigNumberish;
      from: BigNumberish;
      to: BigNumberish;
      gasLimit: BigNumberish;
      gasPerPubdataByteLimit: BigNumberish;
      maxFeePerGas: BigNumberish;
      maxPriorityFeePerGas: BigNumberish;
      paymaster: BigNumberish;
      nonce: BigNumberish;
      value: BigNumberish;
      reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
      data: BytesLike;
      signature: BytesLike;
      factoryDeps: BytesLike[];
      paymasterInput: BytesLike;
      reservedDynamic: BytesLike;
    },
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "payForTransaction(bytes32,bytes32,(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
    _txHash: BytesLike,
    _suggestedSignedHash: BytesLike,
    _transaction: {
      txType: BigNumberish;
      from: BigNumberish;
      to: BigNumberish;
      gasLimit: BigNumberish;
      gasPerPubdataByteLimit: BigNumberish;
      maxFeePerGas: BigNumberish;
      maxPriorityFeePerGas: BigNumberish;
      paymaster: BigNumberish;
      nonce: BigNumberish;
      value: BigNumberish;
      reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
      data: BytesLike;
      signature: BytesLike;
      factoryDeps: BytesLike[];
      paymasterInput: BytesLike;
      reservedDynamic: BytesLike;
    },
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  prepareForPaymaster(
    _txHash: BytesLike,
    _possibleSignedHash: BytesLike,
    _transaction: {
      txType: BigNumberish;
      from: BigNumberish;
      to: BigNumberish;
      gasLimit: BigNumberish;
      gasPerPubdataByteLimit: BigNumberish;
      maxFeePerGas: BigNumberish;
      maxPriorityFeePerGas: BigNumberish;
      paymaster: BigNumberish;
      nonce: BigNumberish;
      value: BigNumberish;
      reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
      data: BytesLike;
      signature: BytesLike;
      factoryDeps: BytesLike[];
      paymasterInput: BytesLike;
      reservedDynamic: BytesLike;
    },
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "prepareForPaymaster(bytes32,bytes32,(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
    _txHash: BytesLike,
    _possibleSignedHash: BytesLike,
    _transaction: {
      txType: BigNumberish;
      from: BigNumberish;
      to: BigNumberish;
      gasLimit: BigNumberish;
      gasPerPubdataByteLimit: BigNumberish;
      maxFeePerGas: BigNumberish;
      maxPriorityFeePerGas: BigNumberish;
      paymaster: BigNumberish;
      nonce: BigNumberish;
      value: BigNumberish;
      reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
      data: BytesLike;
      signature: BytesLike;
      factoryDeps: BytesLike[];
      paymasterInput: BytesLike;
      reservedDynamic: BytesLike;
    },
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  validateTransaction(
    _txHash: BytesLike,
    _suggestedSignedHash: BytesLike,
    _transaction: {
      txType: BigNumberish;
      from: BigNumberish;
      to: BigNumberish;
      gasLimit: BigNumberish;
      gasPerPubdataByteLimit: BigNumberish;
      maxFeePerGas: BigNumberish;
      maxPriorityFeePerGas: BigNumberish;
      paymaster: BigNumberish;
      nonce: BigNumberish;
      value: BigNumberish;
      reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
      data: BytesLike;
      signature: BytesLike;
      factoryDeps: BytesLike[];
      paymasterInput: BytesLike;
      reservedDynamic: BytesLike;
    },
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "validateTransaction(bytes32,bytes32,(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
    _txHash: BytesLike,
    _suggestedSignedHash: BytesLike,
    _transaction: {
      txType: BigNumberish;
      from: BigNumberish;
      to: BigNumberish;
      gasLimit: BigNumberish;
      gasPerPubdataByteLimit: BigNumberish;
      maxFeePerGas: BigNumberish;
      maxPriorityFeePerGas: BigNumberish;
      paymaster: BigNumberish;
      nonce: BigNumberish;
      value: BigNumberish;
      reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
      data: BytesLike;
      signature: BytesLike;
      factoryDeps: BytesLike[];
      paymasterInput: BytesLike;
      reservedDynamic: BytesLike;
    },
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  callStatic: {
    executeTransaction(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    "executeTransaction(bytes32,bytes32,(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    executeTransactionFromOutside(
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    "executeTransactionFromOutside((uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    payForTransaction(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    "payForTransaction(bytes32,bytes32,(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    prepareForPaymaster(
      _txHash: BytesLike,
      _possibleSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    "prepareForPaymaster(bytes32,bytes32,(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
      _txHash: BytesLike,
      _possibleSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    validateTransaction(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<string>;

    "validateTransaction(bytes32,bytes32,(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    executeTransaction(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "executeTransaction(bytes32,bytes32,(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    executeTransactionFromOutside(
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "executeTransactionFromOutside((uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    payForTransaction(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "payForTransaction(bytes32,bytes32,(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    prepareForPaymaster(
      _txHash: BytesLike,
      _possibleSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "prepareForPaymaster(bytes32,bytes32,(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
      _txHash: BytesLike,
      _possibleSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    validateTransaction(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "validateTransaction(bytes32,bytes32,(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    executeTransaction(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "executeTransaction(bytes32,bytes32,(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    executeTransactionFromOutside(
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "executeTransactionFromOutside((uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    payForTransaction(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "payForTransaction(bytes32,bytes32,(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    prepareForPaymaster(
      _txHash: BytesLike,
      _possibleSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "prepareForPaymaster(bytes32,bytes32,(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
      _txHash: BytesLike,
      _possibleSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    validateTransaction(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "validateTransaction(bytes32,bytes32,(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256[4],bytes,bytes,bytes32[],bytes,bytes))"(
      _txHash: BytesLike,
      _suggestedSignedHash: BytesLike,
      _transaction: {
        txType: BigNumberish;
        from: BigNumberish;
        to: BigNumberish;
        gasLimit: BigNumberish;
        gasPerPubdataByteLimit: BigNumberish;
        maxFeePerGas: BigNumberish;
        maxPriorityFeePerGas: BigNumberish;
        paymaster: BigNumberish;
        nonce: BigNumberish;
        value: BigNumberish;
        reserved: [BigNumberish, BigNumberish, BigNumberish, BigNumberish];
        data: BytesLike;
        signature: BytesLike;
        factoryDeps: BytesLike[];
        paymasterInput: BytesLike;
        reservedDynamic: BytesLike;
      },
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;
  };
}
