/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ICompressor } from "./ICompressor";

export class ICompressorFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICompressor {
    return new Contract(address, _abi, signerOrProvider) as ICompressor;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_bytecode",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "_rawCompressedData",
        type: "bytes",
      },
    ],
    name: "publishCompressedBytecode",
    outputs: [
      {
        internalType: "bytes32",
        name: "bytecodeHash",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_numberOfStateDiffs",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_enumerationIndexSize",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "_stateDiffs",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "_compressedStateDiffs",
        type: "bytes",
      },
    ],
    name: "verifyCompressedStateDiffs",
    outputs: [
      {
        internalType: "bytes32",
        name: "stateDiffHash",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
];
