/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IComplexUpgrader } from "./IComplexUpgrader";

export class IComplexUpgraderFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IComplexUpgrader {
    return new Contract(address, _abi, signerOrProvider) as IComplexUpgrader;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_delegateTo",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_calldata",
        type: "bytes",
      },
    ],
    name: "upgrade",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];
