/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IImmutableSimulator } from "./IImmutableSimulator";

export class IImmutableSimulatorFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IImmutableSimulator {
    return new Contract(address, _abi, signerOrProvider) as IImmutableSimulator;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_dest",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_index",
        type: "uint256",
      },
    ],
    name: "getImmutable",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_dest",
        type: "address",
      },
      {
        components: [
          {
            internalType: "uint256",
            name: "index",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "value",
            type: "bytes32",
          },
        ],
        internalType: "struct ImmutableData[]",
        name: "_immutables",
        type: "tuple[]",
      },
    ],
    name: "setImmutables",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
