/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ImmutableSimulatorInterface extends ethers.utils.Interface {
  functions: {
    "getImmutable(address,uint256)": FunctionFragment;
    "setImmutables(address,tuple[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getImmutable",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setImmutables",
    values: [string, { index: BigNumberish; value: BytesLike }[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getImmutable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setImmutables",
    data: BytesLike
  ): Result;

  events: {};
}

export class ImmutableSimulator extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ImmutableSimulatorInterface;

  functions: {
    getImmutable(
      _dest: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getImmutable(address,uint256)"(
      _dest: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setImmutables(
      _dest: string,
      _immutables: { index: BigNumberish; value: BytesLike }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setImmutables(address,tuple[])"(
      _dest: string,
      _immutables: { index: BigNumberish; value: BytesLike }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  getImmutable(
    _dest: string,
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getImmutable(address,uint256)"(
    _dest: string,
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  setImmutables(
    _dest: string,
    _immutables: { index: BigNumberish; value: BytesLike }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setImmutables(address,tuple[])"(
    _dest: string,
    _immutables: { index: BigNumberish; value: BytesLike }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    getImmutable(
      _dest: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getImmutable(address,uint256)"(
      _dest: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    setImmutables(
      _dest: string,
      _immutables: { index: BigNumberish; value: BytesLike }[],
      overrides?: CallOverrides
    ): Promise<void>;

    "setImmutables(address,tuple[])"(
      _dest: string,
      _immutables: { index: BigNumberish; value: BytesLike }[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getImmutable(
      _dest: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getImmutable(address,uint256)"(
      _dest: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setImmutables(
      _dest: string,
      _immutables: { index: BigNumberish; value: BytesLike }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setImmutables(address,tuple[])"(
      _dest: string,
      _immutables: { index: BigNumberish; value: BytesLike }[],
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getImmutable(
      _dest: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getImmutable(address,uint256)"(
      _dest: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setImmutables(
      _dest: string,
      _immutables: { index: BigNumberish; value: BytesLike }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setImmutables(address,tuple[])"(
      _dest: string,
      _immutables: { index: BigNumberish; value: BytesLike }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
