/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MockContractInterface extends ethers.utils.Interface {
  functions: {
    "setResult(tuple)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "setResult",
    values: [{ input: BytesLike; failure: boolean; returnData: BytesLike }]
  ): string;

  decodeFunctionResult(functionFragment: "setResult", data: BytesLike): Result;

  events: {
    "Called(uint256,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Called"): EventFragment;
}

export class MockContract extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MockContractInterface;

  functions: {
    setResult(
      result: { input: BytesLike; failure: boolean; returnData: BytesLike },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setResult((bytes,bool,bytes))"(
      result: { input: BytesLike; failure: boolean; returnData: BytesLike },
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  setResult(
    result: { input: BytesLike; failure: boolean; returnData: BytesLike },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setResult((bytes,bool,bytes))"(
    result: { input: BytesLike; failure: boolean; returnData: BytesLike },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    setResult(
      result: { input: BytesLike; failure: boolean; returnData: BytesLike },
      overrides?: CallOverrides
    ): Promise<void>;

    "setResult((bytes,bool,bytes))"(
      result: { input: BytesLike; failure: boolean; returnData: BytesLike },
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    Called(value: null, data: null): EventFilter;
  };

  estimateGas: {
    setResult(
      result: { input: BytesLike; failure: boolean; returnData: BytesLike },
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setResult((bytes,bool,bytes))"(
      result: { input: BytesLike; failure: boolean; returnData: BytesLike },
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    setResult(
      result: { input: BytesLike; failure: boolean; returnData: BytesLike },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setResult((bytes,bool,bytes))"(
      result: { input: BytesLike; failure: boolean; returnData: BytesLike },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
