/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { DiamondUpgradeInit3 } from "./DiamondUpgradeInit3";

export class DiamondUpgradeInit3Factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<DiamondUpgradeInit3> {
    return super.deploy(overrides || {}) as Promise<DiamondUpgradeInit3>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): DiamondUpgradeInit3 {
    return super.attach(address) as DiamondUpgradeInit3;
  }
  connect(signer: Signer): DiamondUpgradeInit3Factory {
    return super.connect(signer) as DiamondUpgradeInit3Factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DiamondUpgradeInit3 {
    return new Contract(address, _abi, signerOrProvider) as DiamondUpgradeInit3;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_priorityTxMaxGasLimit",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_allowList",
        type: "address",
      },
      {
        internalType: "contract IVerifier",
        name: "_verifier",
        type: "address",
      },
    ],
    name: "upgrade",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610195806100206000396000f3fe60806040526004361061001e5760003560e01c80632fed1f2914610023575b600080fd5b61003661003136600461011d565b610048565b60405190815260200160405180910390f35b600061005481806100d0565b50601a929092556013805473ffffffffffffffffffffffffffffffffffffffff9283167fffffffffffffffffffffffff000000000000000000000000000000000000000091821617909155600a80549290931691161790557f33774e659306e47509050e97cb651e731180a42d458212294d30751925c551a290565b506100df9060078101906100e2565b50565b5b808211156100f757600081556001016100e3565b5090565b73ffffffffffffffffffffffffffffffffffffffff811681146100df57600080fd5b60008060006060848603121561013257600080fd5b833592506020840135610144816100fb565b91506040840135610154816100fb565b80915050925092509256fea2646970667358221220272b7bc95c0863d9345dedfa7012a025d9c26c5c9f10d32b24d30c9ca980c23f64736f6c63430008140033";
