/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { DummyERC20NoTransferReturnValue } from "./DummyERC20NoTransferReturnValue";

export class DummyERC20NoTransferReturnValueFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<DummyERC20NoTransferReturnValue> {
    return super.deploy(
      overrides || {}
    ) as Promise<DummyERC20NoTransferReturnValue>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): DummyERC20NoTransferReturnValue {
    return super.attach(address) as DummyERC20NoTransferReturnValue;
  }
  connect(signer: Signer): DummyERC20NoTransferReturnValueFactory {
    return super.connect(signer) as DummyERC20NoTransferReturnValueFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DummyERC20NoTransferReturnValue {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as DummyERC20NoTransferReturnValue;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5060b78061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063a9059cbb14602d575b600080fd5b603c6038366004603e565b5050565b005b60008060408385031215605057600080fd5b823573ffffffffffffffffffffffffffffffffffffffff81168114607357600080fd5b94602093909301359350505056fea2646970667358221220dd890623aaa548dd43864dd628fb3df0eee6eba4a2143966bd84d72760e39e9464736f6c63430008140033";
