/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { EventOnFallback } from "./EventOnFallback";

export class EventOnFallbackFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<EventOnFallback> {
    return super.deploy(overrides || {}) as Promise<EventOnFallback>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): EventOnFallback {
    return super.attach(address) as EventOnFallback;
  }
  connect(signer: Signer): EventOnFallbackFactory {
    return super.connect(signer) as EventOnFallbackFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EventOnFallback {
    return new Contract(address, _abi, signerOrProvider) as EventOnFallback;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "msgSender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "Called",
    type: "event",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060e98061001e6000396000f3fe60806040527f998729e624ef59107d5781f8c021b04a5d7b5153dd0ef79e7a08a9f8ab40a5a33334600036604051603894939291906042565b60405180910390a1005b73ffffffffffffffffffffffffffffffffffffffff8516815283602082015260606040820152816060820152818360808301376000818301608090810191909152601f9092017fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe0160101939250505056fea2646970667358221220328e24d14fa01bcad541dc2705fce4b910cca104ac245f92417db2d42c6b218f64736f6c63430008140033";
