/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { RevertReceiveAccount } from "./RevertReceiveAccount";

export class RevertReceiveAccountFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<RevertReceiveAccount> {
    return super.deploy(overrides || {}) as Promise<RevertReceiveAccount>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): RevertReceiveAccount {
    return super.attach(address) as RevertReceiveAccount;
  }
  connect(signer: Signer): RevertReceiveAccountFactory {
    return super.connect(signer) as RevertReceiveAccountFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): RevertReceiveAccount {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as RevertReceiveAccount;
  }
}

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "revertReceive",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "newValue",
        type: "bool",
      },
    ],
    name: "setRevertReceive",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506000805460ff191690556101548061002a6000396000f3fe60806040526004361061002d5760003560e01c8063607e2cb21461004c578063aa4593dc1461009857600080fd5b366100475760005460ff1615610045576100456100c6565b005b600080fd5b34801561005857600080fd5b506100456100673660046100f5565b600080547fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff0016911515919091179055565b3480156100a457600080fd5b506000546100b29060ff1681565b604051901515815260200160405180910390f35b7f4e487b7100000000000000000000000000000000000000000000000000000000600052600160045260246000fd5b60006020828403121561010757600080fd5b8135801515811461011757600080fd5b939250505056fea264697066735822122027a65f63dab95cfc04004afbd97b2a109d94da16d038735e87bd1196d4eaa7c664736f6c63430008140033";
