/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { UnsafeBytesTest } from "./UnsafeBytesTest";

export class UnsafeBytesTestFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<UnsafeBytesTest> {
    return super.deploy(overrides || {}) as Promise<UnsafeBytesTest>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): UnsafeBytesTest {
    return super.attach(address) as UnsafeBytesTest;
  }
  connect(signer: Signer): UnsafeBytesTestFactory {
    return super.connect(signer) as UnsafeBytesTestFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UnsafeBytesTest {
    return new Contract(address, _abi, signerOrProvider) as UnsafeBytesTest;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_bytes",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "_start",
        type: "uint256",
      },
    ],
    name: "readAddress",
    outputs: [
      {
        internalType: "address",
        name: "readValue",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "offset",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_bytes",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "_start",
        type: "uint256",
      },
    ],
    name: "readBytes32",
    outputs: [
      {
        internalType: "bytes32",
        name: "readValue",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "offset",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_bytes",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "_start",
        type: "uint256",
      },
    ],
    name: "readUint256",
    outputs: [
      {
        internalType: "uint256",
        name: "readValue",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "offset",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_bytes",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "_start",
        type: "uint256",
      },
    ],
    name: "readUint32",
    outputs: [
      {
        internalType: "uint32",
        name: "readValue",
        type: "uint32",
      },
      {
        internalType: "uint256",
        name: "offset",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610271806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c806369c76df214610051578063af500fb714610085578063e02da32714610085578063f0e9da23146100ad575b600080fd5b61006461005f366004610168565b6100ec565b6040805163ffffffff90931683526020830191909152015b60405180910390f35b610098610093366004610168565b61010d565b6040805192835260208301919091520161007c565b6100c06100bb366004610168565b610123565b6040805173ffffffffffffffffffffffffffffffffffffffff909316835260208301919091520161007c565b6000806101028484600491810182015192910190565b915091509250929050565b6000806101028484602091810182015192910190565b6000806101028484601491810182015192910190565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052604160045260246000fd5b6000806040838503121561017b57600080fd5b823567ffffffffffffffff8082111561019357600080fd5b818501915085601f8301126101a757600080fd5b8135818111156101b9576101b9610139565b604051601f82017fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe0908116603f011681019083821181831017156101ff576101ff610139565b8160405282815288602084870101111561021857600080fd5b82602086016020830137600060209382018401529896909101359650505050505056fea26469706673582212209cf2819759c26877e7ce9c415e67d9038f8647f7015be6bab20c31dcc3ff371564736f6c63430008140033";
